AllCops:
  DisplayCopNames: true
  Exclude:
    - 'Vagrantfile'

Lint/LiteralInCondition:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 18

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FileName:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NumericLiterals:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/WordArray:
  Enabled: false
