language: ruby
rvm:
- 2.3.1
bundler_args: --without integration
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
before_script:
  - bundle exec berks
script:
  - bundle exec foodcritic .
  - bundle exec rspec test/libraries
